FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    libgl1 libglib2.0-0 libpq-dev

COPY . /app/

RUN pip install --no-deps face_recognition==1.3.0 \
    && pip install -r requirements.txt
EXPOSE 8080