# Generated by Django 5.2.7 on 2025-10-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_remove_batch_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_window',
            name='subject',
        ),
    ]
