# Generated by Django 5.2.7 on 2025-10-30 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_remove_attendance_window_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_window',
            name='batch',
        ),
        migrations.AddField(
            model_name='attendance_window',
            name='target_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_windows', to='college.batch'),
        ),
        migrations.AddField(
            model_name='attendance_window',
            name='target_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_windows', to='college.subject'),
        ),
    ]
