# Generated by Django 5.2.8 on 2025-11-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_user_face_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_update_picture',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
