# Generated by Django 5.2.7 on 2025-10-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_alter_course_name_alter_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
