# Generated by Django 5.2.7 on 2025-11-13 17:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=128, null=True),
        ),
    ]
