# Generated by Django 5.2.7 on 2025-11-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_alter_subject_code_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.CharField(blank=True, db_index=True, max_length=9999, null=True),
        ),
    ]
