# Generated by Django 5.2.8 on 2026-02-12 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_announcement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='announcement',
            new_name='college_ann_is_pinn_4ba58d_idx',
            old_name='college_ann_is_pin_idx',
        ),
        migrations.AddField(
            model_name='attendance_window',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
