# Generated by Django 5.2.8 on 2026-02-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_rename_college_ann_is_pin_idx_college_ann_is_pinn_4ba58d_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance_window',
            unique_together={('target_batch', 'target_subject', 'date')},
        ),
    ]
